name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=orca123456_Final1
            -Dsonar.organization=orca123456
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
